__URL__ = '<GitHub URL>'
__DESCRIPTION__ = '<Short description of the project>'
__BUSINESS__ = '<Business>'
__MLE__ = '<MLE red user>'
__MLE_EMAIL__ = '<MLE Email>'
__DS__ = '<DS red user>'
__DS_EMAIL__ = '<DS email>'