mtd_pipeline={'gestion-leads': { 'name_project':'coe-iaaa-iniciatives-priorizacion-leads',
                           'name_subproject':'scoring',  
                            'task':'classification',
                           'type_model':'LGB',      
                            'version':'0.1.0',
                                'kf_name_of_dataset_to_score':'df_preprocess_parquet',
                                'query_feedback':"""bq://SELECT periodo,
                                          id_lead_origen AS idlead,
                                          gst_ind_cuenta_ganado AS lead_priorizacionauc_ami_cls,
                                        FROM `rs-shr-al-analyticsz-prj-ebc1.anl_digital.leads`
                                        WHERE est_lead = 'VALIDO'
                                          AND des_producto_filtro IN ('Salud (AMI)','Salud (Flexi)')
                                          AND fec_lead >= '2019-01-01'
                                          AND id_persona IS NOT NULL""",
                          'selection_method':'undersampling','fix_selection_method':'no',
                           'cfg_parameters':{'n_estimators':7000,'l_rate':0.05,'early_stopping_rounds':5000,'seed':60,'test_size':0.33}, #
                           'name_target':'lead_priorizacionauc_ami_cls',
                           'name_prediction':'lead_priorizacion_ami',
                            'id_features':['idlead','periodo'],
                            'kpi_features':['tiempo_desde_llegada','tiempo_desde_ult_gest'],
                            'captura_features':['tipo_canal_fin'],
                            'in_analyze_features':['plataforma'],
                            'evol_features':'periodo',
                                            'cat_features':[],
                          'cont_features':['tipo_canal',
 'plataforma',
 'finalizado',
 'flag_celular',
 'flag_correo',
 'des_cono_agrup_nuevo',
 'num_edad',
 'cal_gral',
 'mto_max_linea_tc',
 'mto_saldo_sbs',
 'mto_saldo_tc_sbs',
 'flg_tiene_vehiculo',
 'val_scoring_ingreso',
 'flg_fue_cliente_rimac',
 'pc_1',
 'pc_2',
 'dist_cluster0',
 'dist_cluster1',
 'dist_cluster2',
 'dist_min',
 'dist_avg',
 'prom_tiempo_visita',
 'total_visitas',
 'visitas_web',
 'visitas_app',
 'visitas_mobile',
 'tiempo_total_visitas',
 'cuenta_dias_ingreso',
 'visitas_ds',
 'visitas_organico',
 'visitas_pagado',
 'visitas_facebook',
 'visitas_zp',
 'visitas_prod_salud',
 'visitas_prod_veh',
 'visitas_prod_vida',
 'tipo_canal_moda',
 'total_interacciones',
 'interacciones_web',
 'interaccioness_app',
 'interacciones_mobile',
 'interacciones_other',
 'interacciones_fds',
 'interacciones_ds',
 'interacciones_organico',
 'interacciones_pagado',
 'interacciones_google',
 'interacciones_mail',
 'interacciones_facebook',
 'interacciones_zp',
 'interacciones_prod_salud',
 'interacciones_prod_veh',
 'interacciones_prod_vida',
 'interacciones_tipo_formulario',
 'interacciones_tipo_perfil',
 'interacciones_segmento_solicitudes',
 'n_3m',
 'n_6m',
 'n_12m',
 'bin_lead_3m',
 'bin_lead_6m',
 'bin_lead_12m',
 'nse',
 'visitas_dig_3m',
 'visitas_dig_6m',
 'visitas_dig_12m',
 'bin_visit_3m',
 'bin_visit_6m',
 'bin_visit_12m',
 'flag_digital']
,
                            'text_features':[]},
}
