mtd_pipeline={'churn-empresas':{  
                        'name_project':'coe-iaaa-iniciatives-empresas-fuga',
                       'name_subproject':'scoring',
                        'task':'classification',
                        'type_model':'LGB',#
                        'framework_model':'TABULAR',
                       'version':'0.1.0',
                        'selection_method':'stratified', #
                        'cfg_parameters':{'n_estimators':1000,'l_rate':0.09,'early_stopping_rounds':500,'seed':60,'test_size':0.33}, #
                         'name_target':'target',
                        'name_prediction':'per_fuga_empresas_cls',
                        'id_features':['id_contratante','id_poliza','ramo','periodo'],
                        'obs_features':['id_contratante','periodo'],
                            'kpi_features':'ctd_operaciones',
                        'subpoblation_features':'cer_id_ramo',
                    'subpoblation_values':['AX-SOAT','AX-VEHI'],
                       'cat_features':[ 'des_ubigeo',
                                       'des_departamento', 'cer_id_ramo', 'ext_ciiu_v4', 'ext_sector_empresa',
                                       'des_provincia', 'segmento_cliente', 'des_tamano_empresa_2',
                                       'id_producto', 'des_grupo_economico', 'des_distrito'],#
                       'cont_features':['ctd_operaciones', 'mto_prima_anual_usd_3a', 'cal_cpp_dif_12m', 
                                        'cal_dud_dif_1m', 'mto_prima_anual_usd_2a', 'ctd_certificados_diff_2', 
                                        'cal_cpp_dif_2m', 'cal_cpp_dif_1m', 'flg_mayor_riesgo_abrev', 
                                        'cal_cpp_dif_6m', 'cal_def_dif_12m', 'cal_per_dif_3m', 'cal_dud', 
                                        'cal_dud_dif_12m', 'cal_ok_dif_6m', 'cal_cpp', 'cal_ok', 'cal_per_dif_12m',
                                        'mto_prima_mensual_usd', 'mto_prima_anual_usd_1a', 'cal_per', 
                                        'ctd_renovaciones_dif_6m', 'cal_ok_dif_1m', 'cal_def_dif_1m', 
                                        'mto_prima_anual_usd_dif_2a', 'ext_ctd_trabajadores', 'cal_def_dif_6m', 
                                    'ctd_renovaciones_dif_2m', 'ctd_certificados_diff_6', 'mto_prima_anual_usd_dif_1a', 
                                        'ctd_renovaciones_cliente', 'mto_prima_anual_usd', 'ctd_renovaciones_dif_1m', 
                                        'ctd_renovaciones_dif_12m', 'ctd_certificados_diff_12', 'cal_def', 'cal_ok_dif_2m', 
                                        'cal_ok_dif_3m', 'ctd_certificados_diff_3', 'mto_prima_emitida_usd', 'cal_ok_dif_12m', 
                                        'cal_per_dif_6m', 'cal_cpp_dif_3m', 'ctd_renovaciones_dif_3m', 'cal_dud_dif_6m', 'cal_def_dif_3m', 
                                        'ctd_renovaciones', 'ctd_certificados_diff_1', 'cal_per_dif_2m', 'ctd_certificados', 
                                        'ctd_personas_contratante', 'ctd_polizas_contratante', 'ctd_riesgos_contratante', 'ctd_productos_contratante',
                                        'ctd_ramos_contratante', 'ctd_polizas_persona', 'ctd_riesgos_persona', 'ctd_productos_persona', 
                                        'ctd_ramos_persona', 'ctd_polizas_anuladas', 'ctd_polizas_anuladas_dif_1m', 'ctd_polizas_anuladas_dif_12m',
                                        'ctd_polizas_anuladas_dif_2m', 'ctd_polizas_anuladas_dif_3m', 'ctd_polizas_anuladas_dif_6m', 'ctd_canales',
                                        'ctd_certificados_vig', 'ctd_meses_ant_cont', 'pj_ctd_productos', 'pj_ctd_productos_dif_12m',
                                        'pj_ctd_productos_dif_1m', 'pj_ctd_productos_dif_2m', 'pj_ctd_productos_dif_3m', 'pj_ctd_productos_dif_6m', 
                                        'pj_ctd_meses_ant_cont', 'pj_flg_mono_riesgo_abrev', 'pj_ctd_corredores', 'ctd_ent_sbs', 'ctd_ent_sbs_dif_12m',
                                        'ctd_ent_sbs_dif_1m', 'ctd_ent_sbs_dif_2m', 'ctd_ent_sbs_dif_3m', 'ctd_ent_sbs_dif_6m', 'mto_credito_corporativo',
                                        'mto_credito_corporativo_dif_12m', 'mto_credito_corporativo_dif_1m', 'mto_credito_corporativo_dif_2m', 
                                        'mto_credito_corporativo_dif_3m', 'mto_credito_corporativo_dif_6m', 'mto_credito_grandes_empresas', 
                                        'mto_credito_grandes_empresas_dif_12m', 'mto_credito_grandes_empresas_dif_1m', 
                                        'mto_credito_grandes_empresas_dif_2m', 'mto_credito_grandes_empresas_dif_3m', 
                                        'mto_credito_grandes_empresas_dif_6m', 'mto_credito_mediana_empresa', 'mto_credito_mediana_empresa_dif_1m', 
                                        'mto_credito_mediana_empresa_dif_2m', 'mto_credito_mediana_empresa_dif_3m', 'mto_credito_mediana_empresa_dif_6m',
                                        'mto_credito_micro_empresa', 'mto_credito_micro_empresa_dif_12m', 'mto_credito_micro_empresa_dif_1m', 
                                        'mto_credito_micro_empresa_dif_2m', 'mto_credito_micro_empresa_dif_3m', 'mto_credito_micro_empresa_dif_6m', 
                                        'mto_credito_pequena_empresa'                                         ],#
    'text_features':[],
                'steps':{'use_preprocess':True,'use_fs':False,'use_hpo':True,'use_training':True},
                    'preprocess':{'steps_cat_preprocess':['null','le'],
                              'steps_cont_preprocess':['skip'],
                              'preprocess_constants':{'num_fill_null':'mean',
                               'num_outlier_range':2.5}
                                 },
                 'tuning':{'n_trials':10},'training':{'n_folds':5}

},
        'laft-empresas': {
                    'name_project':'coe-iaaa-iniciatives-laft-empresas',
                   'name_subproject':'scoring',  
                    'task':'classification',
                   'type_model':'LGB',  
            'framework_model':'TABULAR',
                    'version':'0.3.5',
                  'selection_method':'undersampling','fix_selection_method':'si',
                   'cfg_parameters':{'n_estimators':10000,'l_rate':0.05,'early_stopping_rounds':5000,'seed':60,'test_size':0.33}, #
                   'name_target':'target',
                   'name_prediction':'per_laft_empresas_cls',
                    'id_features':['id_cliente_empresa','periodo'],
                'kpi_features':'pj_mto_prima_anual_usd',
                        'subpoblation_features':'segmento_cliente',
                    'subpoblation_values':['MICRO EMPRESA','PEQUEÑA EMPRESA'],
                       'evol_features':'periodo',
                  'cat_features':['ext_tip_contribuyente',
                   'num_ubigeo_gestion_servicio', 'tip_documento',
                   'ext_ciiu_act_giro_economico', 'ext_ciiu_act_sector',
                   'ext_ciiu_act_seccion', 'ext_tip_tamanio_empresa',
                   'ext_ciiu_act_division',
                   'ext_ciiu_ant_sector',
                    'ext_des_calificacion_rcc',
                   'tipo_empresa', 'des_riesgo_laft',
                   'segmento_cliente', 'ext_seccion', 'tip_empresa_in',
                    'ext_est_empresa',
                   'condicion_sujeto_obligado', 'cal_gral', 'des_entidad_principal',
                   'des_banco_principal', 'des_entidad_tc_principal',
                   'des_entidad_hip_principal', 'rango_max_linea_tc', 'rango_saldo_tc_sbs',
                   'des_cono_agrup_nuevo', 'des_departamento', 'des_distrito',
                   'des_provincia', 'situacion',
                   'pj_des_mayor_riesgo_abrev', 'pj_des_combo_canales',
                   'pj_des_combo_productos', 'pj_des_combo_riesgos',
                   'pj_des_combo_agrup2_prod', 'pj_des_combo_sub_canales',
                                  'des_combo_agrup2_prod',
                   'des_combo_sub_canales', 'des_combo_first_grupos'],
                  'cont_features':['ext_num_trabajadores', 'score_riesgo_laft', 'rank_sector', 'ext_ctd_trabajadores', 
                                   'mto_factura_usd', 'cal_ok', 'cal_cpp', 'cal_def', 'cal_dud', 'cal_per', 'flg_rcc', 
                                   'flg_cli_tc', 'flg_cli_bancos', 'flg_cli_cmac', 'flg_cli_crac', 'flg_cli_edpymes', 
                                   'flg_cli_financieras', 'flg_cred_hipo_sbs', 'ctd_ent_sbs', 'ctd_ent_tc_sbs', 
                                   'ctd_ent_prest_pers_sbs', 'ctd_ent_cred_micro_sbs', 'ctd_ent_cred_hipo_sbs', 
                                   'ctd_ent_cred_peq_emp_sbs', 'ctd_ent_cred_vehi_sbs', 'mto_linea_libre_tc', 'mto_max_linea_tc', 
                                   'indice_consumo_max_linea_tc', 'indice_acido_consumo_max_linea_tc', 'indice_consumo_total_linea_tc', 
                                   'participacion_deuda_vehicular', 'mto_linea_cred_hipo_sbs', 'mto_linea_cred_vehi_sbs', 
                                   'mto_credito_corporativo', 'mto_credito_grandes_empresas', 'mto_credito_mediana_empresa', 
                                   'mto_credito_pequena_empresa', 'mto_credito_micro_empresa', 'mto_credito_otros_empresa', 
                                   'mto_saldo_sbs', 'mto_saldo_tc_sbs', 'mto_saldo_prest_pers_sbs', 'mto_saldo_cred_micro_sbs', 
                                   'mto_saldo_cred_hipo_sbs', 'mto_saldo_cred_peq_emp_sbs', 'mto_saldo_cred_vehi_sbs', 'dep_score_ingreso', 'ingreso_promedio',
                                   'avg_ingreso_trabajadores', 'num_trabajadores_total', 'ctd_ramos', 'mto_total_pago_indemnizado_usd', 
                                   'mto_total_facturado_usd', 'mto_total_reserva_usd', 'ctd_casos_siniestros', 'avg_edad_trabajadores', 
                                   'mto_facturacion_anual_usd', 'ord_rank_2', 'ctd_certificados_diff_1', 'flg_escliente', 'flg_consentimiento',
                                   'flg_criticos', 'flg_direcc', 'flg_laboral', 'flg_masterbase', 'flg_numero', 'flg_personal', 'flg_telef', 
                                   'flg_tiene_vehiculo', 'flg_situacion_baja', 'flg_monoproducto_soat_1', 'flg_monoproducto_soat_2',
                                   'flg_tiene_rrgg_1', 'flg_tiene_rrgg_2', 'flg_tiene_soat_1', 'flg_tiene_soat_2', 'num_productos_1',
                                   'num_productos_2', 'num_riesgos_1', 'num_riesgos_2', 'prima_cliente_1', 'prima_cliente_2', 
                                   'flg_vigente_3', 'flg_breca', 'flg_celular_serv', 'flg_empleado', 'flg_fallecidos', 'flg_mail',
                                   'flg_telef_serv', 'flg_contactar', 'num_meses_sin_trabajo', 'flg_cli_tiene_vida_1', 
                                   'flg_cli_tiene_vida_2', 'flg_cli_tiene_salud_1', 'flg_cli_tiene_salud_2', 'flg_cli_tiene_eps_1', 
                                   'flg_cli_tiene_eps_2', 'flg_cli_tiene_veh_1', 'flg_cli_tiene_veh_2', 'num_cli_productos_dif_1_2',
                                   'num_cli_riesgos_dif_1_2', 'num_cli_tipoprods_dif_1_2', 'num_cli_canales_dif_1_2', 
                                   'mto_cli_prima_vig_cliente_dif_1_2', 'pj_ctd_corredores', 'pj_ctd_canales', 'pj_ctd_riesgos',
                                   'pj_ctd_meses_ant_cont', 'pj_ctd_ramocontables', 'pj_ctd_agrup2_prod', 'pj_ctd_sub_canales', 
                                   'pj_flg_monoproducto', 'pj_flg_mono_riesgo_abrev', 'pj_flg_eps', 'pj_flg_rrgg', 'pj_flg_salud',
                                   'pj_flg_vehi', 'pj_flg_vida', 'pj_ctd_productos_dif_1m', 'pj_ctd_productos_dif_2m',
                                   'pj_ctd_productos_dif_3m', 'pj_ctd_productos_dif_6m', 'pj_ctd_productos_dif_12m', 
                                   'pj_mto_prima_anual_usd', 'riesgo_laft_producto', 'moneda_usada', 'nro_polizas_contratante', 
                                   'nro_productos_contratante', 'mto_derecho_emision_usd', 'mto_prima_contable_usd', 
                                   'ctd_certificados', 'max_num_meses_sin_trabajo', 'ctd_polizas_vig', 
                                   'ctd_pol_contrat', 'ctd_pol_tit', 'ctd_certificados_vig', 'ctd_productos', 'ctd_riesgos',
                                   'ctd_canales', 'ctd_agrup2_prod', 'ctd_sub_canales', 'ctd_productos_dif_1m', 'ctd_productos_dif_2m',
                                   'ctd_riesgos_dif_2m', 'ctd_agrup2_prod_dif_2m', 'ctd_productos_dif_3m', 'ctd_productos_dif_6m', 
                                   'ctd_productos_dif_12m', 'mto_prima_anual_usd', 'mto_avg_prima_contable_usd_12m', 
                                   'mto_prima_contable_usd_all', 'mto_avg_prima_contable_grupos', 'mto_avg_prima_contable_riesgos',
                                   'mto_ratio_inc_prima_contable_12m', 'mto_ratio_inc_prima_contable_hist', 'mto_prima_contable_usd_dif_2m', 
                                   'mto_max_por_cobrar_usd_12m', 'ctd_meses_ant_cont', 'ctd_meses_ant_hist', 'ctd_meses_fue_cliente', 
                                   'ctd_meses_fue_cliente_12m', 'ctd_polizas_venc', 'ctd_dias_max_atraso', 'ctd_max_polizas_venc_12m', 
                                   'ctd_meses_sin_deuda', 'dem_edad', 'rango_edad', 'flg_bbva', 'flg_corredor', 'flg_alto_valor', 
                                   'flg_acci_pers', 'flg_ami', 'flg_domiciliario', 'flg_eps', 'flg_onco', 'flg_rrgg', 'flg_salud',
                                   'flg_soat', 'flg_vehi', 'flg_vida', 'flg_vida_core', 'flg_vida_dev', 'flg_vida_sin_inv', 'flg_worksite', 
                                   'flg_fue_cliente_rimac', 'flg_tuvo_soatvehi_rimac', 'flg_era_cliente_2mesesantes', 'flg_renta_hosp', 
                                   'flg_salud_mod', 'flg_sepelio', 'flg_vid_fut', 'flg_vid_uni', 'flg_produccion', 'flg_ex_armi', 
                                   'flg_ffvv_canales', 'flg_monobbva', 'flg_canal_directo', 'flg_vida_grupo', 'variacion_veh_first_grupos', 
                                   'tiempo_mercado', 'pj_ctd_flgs', 'planilla', 'fact_minus_prima', 'des_nivel_riesgo_prod_len',
                                  'num_antiguedad_cliente', 'pj_ctd_productos', 'ciclo_vida_rimac', 'des_producto_len', 
                                   'des_riesgo_len', 'des_riesgo_abrev_len', 'pol_des_canal_len', 'pol_des_subcanal_len', 
                                   'pol_des_corredor_len', 'pol_des_canalnt_len', 'des_agrupacion_n1_len', 'des_agrupacion_n2_len', 
                                   'des_agrupacion_n3_len'
                                  ],

                    'text_features':[],
                              'steps':{'use_preprocess':True,'use_fs':False,'use_hpo':False,'use_training':True},
              'preprocess':{'steps_cat_preprocess':['null','pareto','le'],
                      'steps_cont_preprocess':['skip'],
                      'preprocess_constants':{'num_fill_null':'mean',
                       'cat_pareto':0.9,
                       'num_outlier_range':2.5}} ,   
                  'training':{'n_folds':0}
                                  },
              'gestion-leads': {
                            'name_project':'coe-iaaa-iniciatives-priorizacion-leads-vehi',
                           'name_subproject':'scoring',  
                            'task':'classification',
                           'type_model':'LGB',      
                  'framework_model':'TABULAR',
                            'version':'0.1.0',
                          'selection_method':'undersampling','fix_selection_method':'no',
                           'cfg_parameters':{'n_estimators':7000,'l_rate':0.05,'early_stopping_rounds':5000,'seed':60,'test_size':0.33}, #
                           'name_target':'cuenta_ganado',
                           'name_prediction':'lead_priorizacion_vehi_cls',
                            'id_features':['idlead','periodo'],
                                  'kpi_features':'tiempo_desde_llegada',
                        'subpoblation_features':'tipo_canal_fin',
                    'subpoblation_values':['Canales Pagados Frubis','Canales No Pagados'],                  
                            'evol_features':'periodo',
                                            'cat_features':['canal_fin','tipo_canal_fin','plataforma','lima_prov','agrup_nse'],
                          'cont_features':['tiempo_desde_llegada', 'tiempo_desde_ult_gest',
                                           'duracion_total_gestiones', 'tiempo_desde_ult_cef',
                                           'duracion_ult_gestion', 'cuenta_marc_manual', 'tiempo_desde_primer_cef',
                                           'prom_tiempo_cef', 'tiempo_prom_entre_gest', 'tiempo_contacto_efectivo',
                                           'tiempo_prom_entre_gest_ini', 'porc_nocontacto',
                                           'cuenta_marc_predictivo', 'tiempo_prom_entre_gest_cef_ini',
                                           'tiempo_prom_entre_gest_cef', 'tiempo_total_visitas_15dias',
                                           'total_nocontactos', 'total_interacciones_15dias', 'numero_gestion',
                                           'prom_tiempo_visita_15dias', 'tiempo_total_visitas_3meses',
                                           'prom_tiempo_visita_3meses', 'prom_tiempo_visita_1',
                                           'interacciones_ds_15dias', 'interacciones_ds_3meses',
                                           'interacciones_web_15dias', 'interacciones_google_15dias',
                                           'total_interacciones_3meses', 'interacciones_prod_veh_15dias',
                                           'interacciones_mobile_3meses', 'interaccioness_app_15dias',
                                           'interacciones_facebook_15dias', 'total_whatsapp',
                                           'interacciones_mobile_15dias', 'total_contactos_efectivos',
                                           'interacciones_web_3meses', 'cuenta_dias_ingreso_3meses',
                                           'marca_whatsapp', 'total_visitas_15dias',],
                            'text_features':[],
              'steps':{'use_preprocess':True,'use_fs':False,'use_hpo':False,'use_training':True},
                  'preprocess':{'steps_cat_preprocess':['null','le'],
                      'steps_cont_preprocess':['skip'],
                      'preprocess_constants':{'num_fill_null':'mean',
                       'cat_pareto':0.9,
                       'num_outlier_range':2.5}},
                 'tuning':{'n_trials':5},'training':{'n_folds':0}                          

              },
              'payment-projection-empresas':{   'name_project':'coe-iaaa-iniciatives-payment-projection-empresas',
                           'name_subproject':'scoring',  
                            'task':'classification',
                             'framework_model':'TABULAR',
                           'type_model':'LGB',      
                            'version':'0.1.0',
                          'selection_method':'stratified','fix_selection_method':'no',
                           'cfg_parameters':{'n_estimators':10000,'l_rate':0.05,'early_stopping_rounds':7000,'seed':60,'test_size':0.33}, #
                           'name_target':'target',
                           'name_prediction':'per_payprojection_empresas_cls',
                         'obs_features':['idresppago','periodo'],
                        'id_features':['cod_producto','idresppago','num_poliza','periodo'],
                        'kpi_features':'monto_dolares',
                        'subpoblation_features':'canal',
                                             'subpoblation_values':['CORREDOR','DIRECTO'],

                                             'evol_features':'periodo',
                       'cat_features':['compania', 'canal',
                                       'tipo_canal', 'tipo_resp_pago', 'riesgo', 'grupo_producto',
                                       'tramo_agrupado', 'tipo_empresa_in', 'segmento', 'rcc_cal_gral',
                                       'departamento', 'provincia', 'distrito', 'tamanio_de_empresa',
                                       'seccion', 'zona', 'cono_agrup_nuevo', 'sector', 'tipo_contribuyente',
                                       'condicion_contribuyente', 'tipo_doc', 'retencion_agrupada',
                                       'sub_tipo_corredor', 'subsegmento_cierre', 'tipo_corredor',
                                       'pj_des_combo_canales', 'pj_des_combo_productos',
                                       'pj_des_combo_riesgos', 'ciiu', 'peor_tramo', 'mejor_tramo',
                                       'CLIENTE_peor_tramo', 'CLIENTE_mejor_tramo'],
                       'cont_features':[ 'antiguedad',
                                     'pj_ctd_productos', 'pj_ctd_tip_productos', 'rcc_cal_ok', 'rcc_cal_cpp', 'rcc_cal_def', 'rcc_cal_dud', 'rcc_cal_per', 
                                    'ratio_tramo1_en_3M', 'ratio_tramo2_en_3M', 'ratio_tramo3_en_3M', 'ratio_tramo4_en_3M', 'cant_docs_pago_hace_3M',
                                     'rank_sector_2018', 'cant_trabaj', 'num_ent_sbs', 'facturacion_avg', 'ngiroact', 'nro_cuotas', 'ext_fec_inscripcion',
                                     'fec_emision_pol', 'fec_fin_vig', 'fec_inic_vig', 'fec_venc_doc',
                                     'distancia_emision_inic_vig_meses', 'distancia_venc_periodo_actual_dias',
                                     'distancia_vigencia_meses', 'pj_ctd_canales', 'pj_ctd_riesgos', 'pj_flg_eps', 'pj_flg_rrgg', 'pj_flg_salud',
                                     'pj_flg_vehi', 'pj_flg_vida', 'pj_mto_prima_anual_usd', 'ratio_monto_tramo1_en_3M',
                                     'ratio_monto_tramo2_en_3M', 'ratio_monto_tramo3_en_3M',
                                     'rcc_cred_all', 'ratio_monto_tramo4_en_3M', 'rcc_cred_corporativo','rcc_cred_grandesemp',
                                     'rcc_cred_medianasemp', 'rcc_cred_pequeniasemp', 'rcc_cred_microemp', 'rcc_cred_otrosemp',
                                     'ratio_n_documentos_diff', 'n_documentos_diff', 'tramo_1_diff', 'tramo_2_diff', 'tramo_3_diff', 'tramo_4_diff',
                                     'nro_de_polizas', 'nro_de_pagos_por_cliente', 'prima_en_polizas', 'prima_en_clientes',
                                     'nro_meses_desde_primer_pago_responsable', 'nro_meses_desde_primer_pago_poliza',
                                     'ciclo_de_vida_doc', 'meses_entre_vigencia_emision', 'meses_entre_vigencia_vencimiento',
                                     'prima_potenc', 'monto_dolares', 'prima', 'monto_tramo1_en_3M','monto_tramo2_en_3M',
                                     'monto_tramo3_en_3M', 'monto_tramo4_en_3M', 'cant_facturas', 'cantidad_renovacion_max',
                                     'ciclo_pago', 'nro_meses_desde_primer_pago', 'nro_meses_desde_primer_pago_documento_mean',
                                     'n_documentos', 'prima_total', 'prima_max', 'cantidad_renovacion_max_max',
                                     'monto_dscto', 'historico_nro_pagos_doc', 'documento_antiguo', 'llave_antiguo',
                                     'poliza_antiguo', 'responsable_antiguo', 'ratio_primert',
                                     'ratio_segundot', 'ratio_tercert', 'ratio_cuartot', 'diversidad_tramo',
                                     'historico_nro_pagos', 'historico_nro_pagos_cliente', 'CLIENTE_prima_total', 'CLIENTE_prima_max',
                                     'CLIENTE_n_documentos', 'CLIENTE_ratio_primert', 'CLIENTE_ratio_segundot', 'CLIENTE_ratio_tercert',
                                     'CLIENTE_ratio_cuartot', 'CLIENTE_num_poliza', 'CLIENTE_cod_producto', 'CLIENTE_cantidad_renovacion_max_max',],
                        'text_features':[],
                         'steps':{'use_preprocess':True,'use_fs':False,'use_hpo':False,'use_training':True},
                    'preprocess': {'steps_cat_preprocess':['null','pareto','le'],
                                          'steps_cont_preprocess':['skip'],
                                          'preprocess_constants':{'num_fill_null':'mean',
                                           'cat_pareto':0.9,
                                           'num_outlier_range':3}
                                  },
                    'tuning':{'n_trials':10},'training':{'n_folds':0}
                         
},
'score-vehicular-renov-persistencia':{'name_project':'coe-iaaa-iniciatives-score_vehicular_renov',
                       'name_subproject':'persistencia',
                        'task':'classification',
                        'type_model':'LGB',
                     'framework_model':'TABULAR',
                       'version':'0.3.0',
                       'selection_method':'stratified', 
                        'name_target':'target',
                         'name_prediction':'perveh_persistenciarenov_vehicular_cls',                                                 
                         'cfg_parameters':{'n_estimators':3000,'l_rate':0.09,'early_stopping_rounds':2000,'seed':60,'test_size':0.33},                           'id_features':['id_persona', 'id_certificado', 'id_vehiculo', 'id_poliza','periodo'],
 
                                                              'kpi_features':'mto_anhos_carro',
                        'subpoblation_features':'des_origen',
                                             'subpoblation_values':['COREANO','JAPONESA'],
                                      
                        'evol_features':'periodo',

                       'cat_features':['pol_des_canal', 'des_combo_canales',
                                       'des_combo_first_grupos', 'tip_trabajador', 'des_act_economica', 'nse',
                                       'nse_24m', 'des_cono_agrup_nuevo', 'des_dep_agrup', 'des_departamento',
                                       'des_lima_agrup', 'des_provincia', 'des_zona',
                                       'des_grado_instruccion',
                                       'des_uso_vehiculo_vehicular', 'des_clase', 'des_marca',
                                       'des_marca_modelo', 'des_origen', 'des_segmento_auto', 'tip_propiedad',
                                       'tip_riesgo', 'cal_gral', 'cal_gral_12m', 'cal_gral_24m', 'cal_gral_6m'],
                       'cont_features':['mto_anhos_carro', 'ctd_renovaciones', 'mto_prima_emitida_usd_acum', 
                                      'mto_suma_asegurada', 'ctd_agrup2_prod', 
                                        'ctd_agrup2_prod_dif_2m', 'ctd_canales', 'ctd_meses_ant_cont', 'ctd_meses_ant_hist', 
                                        'ctd_meses_fue_cliente', 'ctd_meses_sin_deuda', 'ctd_productos', 'ctd_riesgos', 
                                        'ctd_riesgos_dif_2m', 'dem_edad', 'flg_soat', 'mto_avg_prima_contable_grupos', 
                                        'mto_avg_prima_contable_riesgos', 'mto_avg_prima_contable_usd_12m',
                                        'mto_prima_anual_usd', 'mto_prima_contable_usd', 'mto_prima_contable_usd_dif_2m', 
                                        'mto_ratio_inc_prima_contable_hist', 'rango_edad', 'variacion_veh_first_grupos', 
                                        'dep_score_ingreso', 'ingreso_promedio', 'mto_ingreso_0', 'mto_ingreso_12', 
                                        'mto_ingreso_6', 'mto_ingreso_ruc_principal_0', 'mto_ratio_saldo_ingreso', 
                                        'mto_ratio_saldo_tc_ingreso', 'mto_ratio_saldo_veh_ingreso', 
                                        'mto_scoring_ingreso_prom', 'val_scoring_ingreso', 'flg_tiene_soat_1', 
                                        'flg_tiene_soat_2', 'num_productos_1', 'num_productos_2', 'num_riesgos_1', 
                                        'num_riesgos_2', 'prima_cliente_1', 'prima_cliente_2', 'tiene_hijos', 
                                        'antiguedad_vehiculo', 'flg_uso_taxi', 'mto_factor_depreciacion',
                                        'mto_valor_actual', 'flg_chino_hindu', 'mto_valor_nuevo', 'num_anio_fabricacion', 
                                        'num_asientos', 'ctd_siniestros_acum_3', 'nro_vig_sin_siniestro', 
                                        'siniestros_periodo_max', 'siniestros_pasados_max', 'siniestralidad_periodo_acum', 
                                        'mto_usd_beneficio_sin_igv_max_acum', 'mto_usd_beneficio_sin_igv_sum_acum', 'mto_reserva', 
                                        'mto_reserva_1', 'mto_reserva_2', 'mto_reserva_3', 'mto_reserva_usd_6', 'mto_reserva_usd_12', 
                                        'mto_reserva_usd_24', 'ctd_ent_cred_vehi_sbs', 'ctd_ent_cred_vehi_sbs_12m',
                                        'ctd_ent_cred_vehi_sbs_6m', 
                                        'ctd_ent_cred_vehi_sbs_dif_12m', 'ctd_ent_cred_vehi_sbs_dif_6m',
                                        'indice_acido_consumo_max_linea_tc',
                                        'mto_linea_cred_vehi_sbs', 'mto_max_linea_tc', 'mto_max_linea_tc_12m', 'mto_max_linea_tc_24m',
                                        'mto_max_linea_tc_6m', 
                                        'mto_max_linea_tc_dif_12m', 'mto_saldo_cred_hipo_sbs_24m', 'mto_saldo_cred_vehi_sbs',
                                        'mto_saldo_cred_vehi_sbs_12m', 
                                        'mto_saldo_cred_vehi_sbs_4m', 'mto_saldo_cred_vehi_sbs_6m', 'mto_saldo_cred_vehi_sbs_dif_12m', 
                                        'mto_saldo_cred_vehi_sbs_dif_6m', 'mto_saldo_prest_pers_sbs', 'mto_saldo_sbs',
                                        'mto_saldo_sbs_10m', 
                                        'mto_saldo_sbs_12m', 'mto_saldo_sbs_24m', 'mto_saldo_sbs_4m', 'mto_saldo_sbs_6m',
                                        'mto_saldo_sbs_dif_12m', 
                                        'mto_saldo_sbs_dif_6m', 'mto_saldo_tc_sbs', 'mto_saldo_tc_sbs_12m', 'mto_saldo_tc_sbs_24m',
                                        'mto_saldo_tc_sbs_6m', 
                                        'mto_saldo_tc_sbs_dif_12m', 'mto_saldo_tc_sbs_dif_6m', 'participacion_deuda_vehicular',
                                        'ctd_siniestros_cer_1', 
                                        'ctd_siniestros_cer_2', 'ctd_siniestros_cer_3', 'ctd_prev_siniestros_cer_3_acum',
                                        'ctd_siniestros_enferm_ojos_anexos_l12m', 
                                        'ctd_siniestros_sistema_nervioso_l12m',
                                        'ctd_siniestros_sistema_osteomuscular_tejido_conectivo_l12m', 
                                        'ctd_siniestros_transtorno_mental_comportamiento_l12m', 'ctd_siniestros_traumatismo_envenenamiento_otras_consecuencias_l12m',
                                        'ctd_siniestros_enferm_ojos_anexos_l6m', 'ctd_siniestros_sistema_nervioso_l6m', 
                                        'ctd_siniestros_sistema_osteomuscular_tejido_conectivo_l6m', 'ctd_siniestros_transtorno_mental_comportamiento_l6m', 
                                        'ctd_siniestros_traumatismo_envenenamiento_otras_consecuencias_l6m', 'ctd_siniestros_enferm_ojos_anexos_l2m', 
                                        'ctd_siniestros_sistema_nervioso_l2m', 'ctd_siniestros_sistema_osteomuscular_tejido_conectivo_l2m', 
                                        'ctd_siniestros_transtorno_mental_comportamiento_l2m', 'ctd_siniestros_traumatismo_envenenamiento_otras_consecuencias_l2m', 
                                        'flg_ami_last_12m'],
                        'text_features':[],
                                           'steps':{'use_preprocess':True,'use_fs':False,'use_hpo':False,'use_training':True},
                  'preprocess':{'steps_cat_preprocess':['null','pareto','le'],
                      'steps_cont_preprocess':['outlier'],
                      'preprocess_constants':{'num_fill_null':'mean',
                       'cat_pareto':0.9,
                       'num_outlier_range':3}},
                'feature_selection':{'fs_treshold':100,'fs_mode':'gain'},
               'tuning':{'n_trials':10},'training':{'n_folds':0},
                         
},
              'nlp_sentiment':{  
                        'name_project':'coe-iaaa-iniciatives-sentiment-analysis',
                       'name_subproject':'scoring_sentiment',
                        'task':'classification',
                        'type_model':'RL',#
                        'framework_model':'NLP',
                       'version':'0.1.0',
                        'selection_method':'stratified', #
                        'cfg_parameters':{'n_estimators':1000,'min_df':1,'sublinear_tf':True,'use_idf':True,'seed':60,'test_size':0.33}, #
                         'name_target':'score',
                        'name_prediction':'score_prediction',
                        'id_features':['id_review'],
                        'obs_features':['id_review'],
                            'kpi_features':'ctd_operaciones',
                        'subpoblation_features':'platform',
                    'subpoblation_values':['googlemaps','playstore'],
                       'cat_features':[ ],#
                       'cont_features':[],#
    'text_features':'review',
                'steps':{'use_preprocess':False,'use_fs':False,'use_hpo':True,'use_training':True},
                    'preprocess':{'steps_cat_preprocess':['null','le'],
                              'steps_cont_preprocess':['skip'],
                              'preprocess_constants':{'num_fill_null':'mean',
                               'num_outlier_range':2.5}
                                 },
                 'tuning':{'n_trials':50},'training':{'n_folds':5}

}
              
}
mtd_project={'churn-empresas':{  'name_project':'coe-iaaa-iniciatives-empresas-fuga',
                         'url_github' : 'https://github.com/Rimac-Seguros/coe-iaaa-iniciatives-empresas-fuga/tree/exp',
                        'url_jira':'https://rimacseguros.atlassian.net/browse/CAAAMG-100',
                        'description' : 'Fuga_clientes',
                        'business' : 'Tribu_Empresas_Squad_Churn',
                        'mle' : 'Milton_Lopez',
                        'ds' : 'Ronald_Lazaro',},
             'laft-empresas':{  'name_project':'coe-iaaa-iniciatives-laft-empresas',
                         'url_github' : 'https://github.com/Rimac-Seguros/coe-iaaa-iniciatives-laft-empresas/exp',
                        'url_jira':'',
                        'description' : 'Lavado de activos y financiamiento al terrorismo',
                        'business' : 'Area_de_cumplimiento',
                        'mle' : 'Milton_Lopez',
                        'ds' : 'Ronald_Lazaro',},
             'gestion-leads':{  'name_project':'coe-iaaa-iniciatives-priorizacion-leads-vehi',
                         'url_github' : 'https://github.com/Rimac-Seguros/coe-iaaa-iniciatives-priorizacion-leads-vehi',
                        'url_jira':'',
                        'description' :  'Modelo de Priorización del producto Seguro Vehicular',
                        'business' : 'Producto Seguro Vehicular',
                        'mle' : 'Milton_Lopez',
                        'ds' : 'Ricardo_Quiroz',},
            'payment-projection-empresas':{  'name_project':'coe-iaaa-iniciatives-payment-projection-empresas',
                         'url_github' : 'https://github.com/Rimac-Seguros/coe-iaaa-iniciatives-payment-projection-empresas',
                        'url_jira':'',
                        'description' :  'Prioridades en el recupero de monto en clientes morosos',
                        'business' : 'GSP',
                        'mle' : 'Milton_Lopez',
                        'ds' : 'Ronald_Lazaro',},
             'score-vehicular-renov-persistencia':{  'name_project':'coe-iaaa-iniciatives-score-vehicular-renov',
                         'url_github' : 'https://github.com/Rimac-Seguros/coe-iaaa-iniciatives-score-vehicular-renov',
                        'url_jira':'',
                        'description' :  'Proyecto score vehicular renovaciones',
                        'business' : 'Pricing',
                        'mle' : 'Milton_Lopez',
                        'ds' : '',}            
            }